name: terraform-fmt-check
author: Antoine Cavaille

inputs:
  terraform-path:
    description: 'Path of your terraform resources'
    required: true
    default: '.'

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.terraform-path }}

branding:
  icon: life-buoy
  color: gray-dark
